### ISSUE TITLE
Call to set() on non-object (Kirby Registry)

### ISSUE THREAD

**Issue by Christo44** [AugustMiller/kirby-map-field#11]
I installed the plugin renamed the folder to maps. I added an API Key from the Google API Console, added in config.php

When I reload the page this is what I got:

```
Call to a member function set() on a non-object in /site/plugins/map/map.php on line 3
```
Not sure what I'm doing wrong ?

**Comment by AugustMiller** [comment]
What version of Kirby are you using? This looks like a problem with accessing the [Kirby Registry](https://getkirby.com/docs/developer-guide/plugins/registry), which was introduced in v2.3.0.

**Comment by AugustMiller** [comment]
Just added a note in the Readme about compatibility!

**Comment by Christo44** [comment]
I'm using 2.4.1

**Comment by AugustMiller** [comment]
Any kind of modifications done to `site.php`?

All the error is saying is that there's a problem accessing the global `$kirby` variable, which should be set at this point in the execution. Haven't seen this problem, before!

Could you create a new plugin?

1. Create `site/plugins/test.php`
2. Add `<?php echo $kirby::$version;` to that file
3. Reload your page

If you get the same error, then something is wrong with your installation, and `$kirby` isn't getting properly defined. Otherwise, we'll need to do some more troubleshooting!

**Comment by Christo44** [comment]
By `site.php` do you mean `/core/site.php` ? If so then no not manually by me. I did not modify it that I'm aware of.

I've created the plugin, and this is very interesting:
`Fatal error: Class name must be a valid object or a string in /Users/christosteyn/Sites/hba2/site/plugins/test.php on line 1`

**Comment by Christo44** [comment]
This however does produce without errors my kirby version:
`<?php
echo kirby()->version() ;
?>
`

**Comment by Christo44** [comment]
I upgraded kirby and now it's working :)

**Comment by AugustMiller** [comment]
That's good! But I'm still curious what would have caused this, in the first place—also not sure what the error is that you'd encountered with `test.php`…

Sorry I couldn't be of more help! If you have a moment, let me know what else you tried, and I'll see if I can replicate it.

_Edit: Just tested with 2.3.0… seems to be working!_

**Comment by Christo44** [comment]
Perhaps If I had enabled the debugging mode it would have helped more, meaning I could have given you better feedback.

**Comment by AugustMiller** [comment]
I'll assume that the root issue here was an installation error, for now—not sure where you upgraded _to_, from 2.4.1 (that's the latest release, as of this comment), but if a fresh install helped, that's good!

If anyone encounters a similar issue, please re-open this issue!
