### ISSUE TITLE
Fatal error: Class 'InputField' not found

### ISSUE THREAD

**Issue by jklue** [AugustMiller/kirby-map-field#14]
I'm doing something really wrong I think. After I install the plugin I see this error in the dashboard:

`Fatal error: Class 'InputField' not found in .../site/plugins/map/map.php on line 1`

But I see the InputField Class defined in panel/app/fields/input/input.php. How does it not see it?

**Comment by AugustMiller** [comment]
I've got a hunch! Have you included just the `fields/map` folder in your plugins directory?

You'll need to download this entire repository, and drop the whole thing into the plugins folder, naming it `map`.

There may be some issues with how Kirby auto-loads base plugin files (and then lazy-loads field definitions, via [the registry functions](https://github.com/AugustMiller/kirby-map-field/blob/master/map.php#L3)) that causes this to blow up. Perhaps other field definitions aren't loaded in time for a field to be declared in the main plugin file… which would explain why field-only plugins that use this structure can live in the `site/fields` directory (they are loaded only when the base field definitions are ready).

Let me know how this works?

**Comment by jklue** [comment]
Yes, you were spot on. Thanks for being awesome.

**Comment by AugustMiller** [comment]
Great! Closing.
